[package]
name = "sk_common"
version = "0.0.1"
description = "sk chain common"
authors = ["cc"]
license = ""
repository = ""
edition = "2021"
rust-version = "1.57"

[dependencies]
ed25519-dalek = "1.0.1"
libipld = "0.14"
num-traits = "0.2"
num-bigint = "0.4"