FROM rust:1.64 as builder
# Use prebuilt builder image
# FROM rust:1.50-prebuilt as builder
RUN apt-get update
RUN apt-get install apt-utils -y
RUN apt-get install software-properties-common -y
RUN wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | apt-key add -
RUN apt-add-repository 'deb https://apt.kitware.com/ubuntu/ bionic main'
RUN apt-get update
RUN apt-get -y dialog
RUN apt-get install -y llvm cmake make
RUN apt-get install -y build-essential libdbus-glib-1-dev libgirepository1.0-dev
RUN apt-get install -y libsoup2.4
RUN apt-get install -y libwebkit2gtk-4.0-dev libssl-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev
RUN apt-get install -y libjemalloc-dev

# apt install --assume-yes git clang curl libssl-dev llvm libudev-dev make protobuf-compiler 
# apt install build-essential libdbus-glib-1-dev libgirepository1.0-dev

# apt-get install -y libsdl-pango-dev
# gir1.2-javascriptcoregtk-4.0
# apt-get install build-essential libgtk-3-dev

# docker run -d -v /home:/cc 37a7a698e09e /bin/sh -c "while true; do echo hello world; sleep 1; done"
# docker exec -it  61514df87ffa  bash